### PR TITLE
Add npm config to cdn url resolution

### PR DESCRIPTION
**Pull request by bingenito**
Provide support for configuring cdn url in npm config.  Match behavior of other similar configuration by processing npm config first followed by path.

### CODE REVIEW

**Comment by ksathyanm** [comment]
Any updates on this PR?

**Comment by ksathyanm** [comment]
@dmlemeshko ping

**Review by dmlemeshko — APPROVED** [review]
Thank you! LGTM

**Comment by bingenito** [comment]
Thank you @dmlemeshko for your work on this project

**Pull request merged**
